### ISSUE TITLE
Support for ApplePay

### ISSUE THREAD

**Issue by Douglasdf** [Pikaju/FlutterBraintree#8]
Is there any sample for ApplePay ?

**Comment by Pikaju** [comment]
I am currently unable to implement this, as I don't have any Apple devices.

**Comment by JulioBoffo** [comment]
Hello @Pikaju,  

Is there any way to open the drop-in with just the apple pay option?

We tried to send the enableCard = false flag and change it on the Braintree portal, but the option in the drop-in still remained.

Can you help us?

Thanks.

**Comment by JulioBoffo** [comment]
Hello @Pikaju,

Is there any way to open the drop-in with just the Google Pay option?
We tried to send the enableCard = false flag and change it on the Braintree portal, but the option in the 
drop-in still remained.Can you help us?

Thanks.

**Comment by Pikaju** [comment]
> Hello @Pikaju,
> 
> Is there any way to open the drop-in with just the Google Pay option?
> We tried to send the enableCard = false flag and change it on the Braintree portal, but the option in the
> drop-in still remained.Can you help us?
> 
> Thanks.

This may be a bug, I'll have to look into it.

**Comment by HareshGediya** [comment]
Hello, @JulioBoffo @Pikaju 
enableCard = false option did not handle in the swift plugin so that it will not working in iOS. I add those codes in plugin also make pull request for this. @Pikaju you can check in PR.

**Comment by Pikaju** [comment]
Thank you @HareshGediya ! I merged your PR, so this issue should be fixed in version `1.0.3`.

**Comment by Pikaju** [comment]
Wait this was a separate issue...

**Comment by HareshGediya** [comment]
Hello, @Pikaju 
I add Apple Pay support in Drop-In UI. I make a pull request for Apple Pay support.

**Comment by Pikaju** [comment]
Thank you @HareshGediya. I merged it in. Version `1.1.0` should come with ApplePay support.

**Comment by sagar440** [comment]
Hi @Pikaju, I have done with all the required steps in Xcode, App Store Connect & Braintree control panel side. But the option of Apple pay in drop in is not showing. is there any further steps to enable Apple pay or it is the issue of regions(Country). i'm testing it in india. Although my region is not in the list of apple pay supported countries. i want to just show the apple pay option so that people in supported countries will be able use it.
Thanks in advance for any help or suggestions.

**Comment by HareshGediya** [comment]
@sagar440 Please check the official Braintree setup for Apple Pay, and configure as suggest in that doc. After configuring your Braintree, Apple account, and Xcode adds bellow request into your project. Apple Pay option only available in supported countries otherwise it will not show.

`var request = BraintreeDropInRequest(
  tokenizationKey: "you to set your token key from Braintree Panel",
  collectDeviceData: true,
  applePayRequest: BraintreeApplePayRequest(
    amount: 10.5,
    countryCode: "US",
    currencyCode: "USD",
    displayName: "Testing Apple Pay",
    appleMerchantID: "merchant id from apple account",
  ),
);

BraintreeDropInResult result = await BraintreeDropIn.start(request);`

**Comment by sagar440** [comment]
Thanks @HareshGediya for your quick response. And i have already added **applePayRequest**  code in my project but no success. I just wants to know is there any way to test it in my region(India)? it seems you are also an indian. you have tested it ?
Thanks,
